### ISSUE TITLE
Projects aren't deleted

### ISSUE THREAD

**Issue by noclat** [JMDidon/synapp.se#1]
When I put a folder in the trash and then sync the projects, the matching project isn't deleted.

**Comment by JMDidon** [comment]
I also encoutered this bug. To permanently delete the folder, I had to go to the Dropbox's website and erase it from the website.

**Comment by noclat** [comment]
Yep, but the project just duplicates itself in Synappse, so this will need further researches.

**Comment by noclat** [comment]
Seems solved.
