### ISSUE TITLE
Projects name conflicts

### ISSUE THREAD

**Issue by noclat** [JMDidon/synapp.se#11]
Must prevent two projects form having the same slug.
@JMDidon: on adding/editing a project, make sure there's no duplicate.
**@Me**: on sync, make sure that new folders create unique slugs.

**Comment by JMDidon** [comment]
I've done a little check to verify if a project exists when it is created. For the moment, it doesn't inform the user about why he can't create the new project.

**Comment by noclat** [comment]
The best should be to create it anyway with a temp name like "Project name (2)" ;). (Or keep the same name and just change the slug.)
