### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by JMDidon** [JMDidon/synapp.se#2]
I have two browsers opened and I have the same project opened in both browsers. But the tasks I have in both browsers are different, it seems that it doesn't sync correctly both browsers and that it can't know which one to choose over which one.

**Comment by noclat** [comment]
Did you clean the localStorage object in both browsers?

**Comment by JMDidon** [comment]
Nope, but the usual user won't know that he has to flush his localStorage ^^'

**Comment by noclat** [comment]
Of course. I'm asking to find faster where the problem comes from ;).

**Comment by noclat** [comment]
@JMDidon Is the bug persistent?

**Comment by JMDidon** [comment]
I have a different bug now : I have two projects with the same name but IDs are differents. After flushing my localStorage it seems to be OK.

**Comment by noclat** [comment]
I think this is coming from the updates we make to the project object tree. Let's see how if the bug persists with a stable project object from now on.
