### ISSUE TITLE
Task: assigned users aren't an array

### ISSUE THREAD

**Issue by noclat** [JMDidon/synapp.se#5]
Checkboxes are a little more difficult to handle. They won't return an array on their own.
You should give a look at:
http://stackoverflow.com/questions/14514461/how-can-angularjs-bind-to-list-of-checkbox-values

**Comment by noclat** [comment]
So task.users is now an empty array to prevent chained bugs until you fix that.

**Comment by JMDidon** [comment]
Done, used a multiple select.
