### ISSUE TITLE
Prévenir le panel utilisateurs

### ISSUE THREAD

**Issue by noclat** [JMDidon/synapp.se#51]
Commencer à contacter le panel utilisateur, et voir qui répondra présent au lancement en fin de semaine prochaine.

**Comment by GuillaumeBeck** [comment]
J'en ai déjà deux, je vais passer en revue les adresses mails d'ici le début de semaine

**Comment by noclat** [comment]
Envoie un mail à tous ;).

**Comment by GuillaumeBeck** [comment]
Grave :) C'est ce que j'allais dire après avoir réfléchis deux minutes !
