### ISSUE TITLE
Ajouter/renommer une tâche

### ISSUE THREAD

**Issue by noclat** [JMDidon/synapp.se#61]
- L'utilisateur ajoute une tâche en spécifiant le titre dans un input et en appuyant sur "enter" (ou "retour" sur mobile).
- Lorsque l'utilisateur clique sur une tâche, le titre devient éditable et il peut la renommer  en appuyant sur "enter" (ou "retour" sur mobile).

**Comment by JMDidon** [comment]
Done, à vérifier.
