### ISSUE TITLE
Supprimer une tâche

### ISSUE THREAD

**Issue by noclat** [JMDidon/synapp.se#62]
- Sur mobile, l'utilisateur swipe vers la gauche sur une tâche pour afficher une liste d'options, et swipe vers la droite pour fermer cette liste.
- Sur desktop, cette liste apparaît lors du mouseover d'une tâche.
- Dans cette liste, un bouton permet de supprimer la tâche, en demandant une confirmation.

_On appelle cette liste **liste d'options** pour la suite._

**Comment by JMDidon** [comment]
Done, à vérifier.
