### ISSUE TITLE
Menu des projets

### ISSUE THREAD

**Issue by noclat** [JMDidon/synapp.se#65]
- L'utilisateur peut créer un projet via un input, et valider en appuyant sur "retour".
- Lorsqu'il clique sur un projet, il accède aux tâches.
- Sur le même modèle que les tâches, une liste d'options est disponible via un swipe gauche (mouseover sur desktop).
- Dans cette liste d'options, il y a 3 boutons : 
  - Renommer : ouvre une pop-in avec un champ input et deux boutons pour valider ou annuler l'action.
  - Partager : ouvre le lien de partage dropbox dans une nouvelle fenêtre.
  - Supprimer : demande confirmation puis supprime.

**Comment by JMDidon** [comment]
Done, à vérifier.
